-- https://wiki.multitheftauto.com/wiki/Material_IDs
-- https://wiki.multitheftauto.com/wiki/EngineGetSurfaceProperties
-- https://gameshaker.ucoz.ru/publ/igry/gtasa/id_materialov_kollizii_dlja_gta_sa/31-1-0-177

local MATERIAL_CATEGORY = {
    [0]     = { en_title = 'Default', ru_title = 'По умолчанию' },
    [1]     = { en_title = 'Concrete', ru_title = 'Бетон' },
    [2]     = { en_title = 'Gravel', ru_title = 'Гравий'  },
    [3]     = { en_title = 'Grass', ru_title = 'Трава'  },
    [4]     = { en_title = 'Dirt', ru_title = 'Земля'  },
    [5]     = { en_title = 'Sand', ru_title = 'Песок'  },
    [6]     = { en_title = 'Glass', ru_title = 'Стекло'  },
    [7]     = { en_title = 'Wood', ru_title = 'Дерево'  },
    [8]     = { en_title = 'Metal', ru_title = 'Метал'  },
    [9]     = { en_title = 'Stone', ru_title = 'Камень'  },
    [10]    = { en_title = 'Vegetation', ru_title = 'Растительность'  },
    [11]    = { en_title = 'Water', ru_title = 'Вода' },
    [12]    = { en_title = 'Misc', ru_title = 'Разное' },
}


MATERIALS_LIST = {

    -- Default
    [0]     = { group_id = 0, group_title = 'Default', en_title = 'Default', ru_title = 'По умолчанию' },
    [1]     = { group_id = 0, group_title = 'Default', en_title = 'Tarmac', ru_title = 'Дорога, шоссе' },
    [2]     = { group_id = 0, group_title = 'Default', en_title = 'Tarmac (damaged)', ru_title = 'Шоссе' },
    [3]     = { group_id = 0, group_title = 'Default', en_title = 'Tarmac (really damaged)', ru_title = 'Асфальтированное шоссе' },
    
    -- Concrete
    [4]     = { group_id = 1, group_title = 'Concrete', en_title = 'Pavement', ru_title = 'Тротуарный бетон' },
    [5]     = { group_id = 1, group_title = 'Concrete', en_title = 'Pavement (damaged)', ru_title = 'Тротуарный бордюр/обочина' },
    [7]     = { group_id = 1, group_title = 'Concrete', en_title = 'Concrete (damaged)', ru_title = 'Бетонная обочина дороги' },
    [8]     = { group_id = 1, group_title = 'Concrete', en_title = 'Painted Ground', ru_title = 'Бетонная окрашенная поверхность' },
    [34]    = { group_id = 1, group_title = 'Concrete', en_title = 'Concrete (beach)', ru_title = 'Бетон на пляже' },
    [89]    = { group_id = 1, group_title = 'Concrete', en_title = 'Concrete', ru_title = 'Бетон' },
    [127]   = { group_id = 1, group_title = 'Concrete', en_title = 'Poolside', ru_title = 'Поверхность бассейна и вокруг него' },
    [135]   = { group_id = 1, group_title = 'Concrete', en_title = 'Docklands', ru_title = 'Бетон в раене доков' },
    [136]   = { group_id = 1, group_title = 'Concrete', en_title = 'Industrial', ru_title = 'Бетон в промышленной зоне' },
    [137]   = { group_id = 1, group_title = 'Concrete', en_title = 'Industrial Jetty', ru_title = 'Бетонная поверхность промышленной Jetty' },
    [138]   = { group_id = 1, group_title = 'Concrete', en_title = 'Concrete (litter)', ru_title = 'Бетонная подстилка' },
    [139]   = { group_id = 1, group_title = 'Concrete', en_title = 'Alley Rubbish', ru_title = 'Бетонная алея мусора' },
    [144]   = { group_id = 1, group_title = 'Concrete', en_title = 'Airport Ground', ru_title = 'Бетонная поверхность аэропорта' },
    [165]   = { group_id = 1, group_title = 'Concrete', en_title = 'Floor (concrete)', ru_title = 'Бетонный пол на этаже/балконе' },

    -- Gravel
    [6]     = { group_id = 2, group_title = 'Gravel', en_title = 'Gravel', ru_title = 'Гравий' },
    [85]    = { group_id = 2, group_title = 'Gravel', en_title = 'Roadside', ru_title = 'Придорожный гравий/щебень' },
    [101]   = { group_id = 2, group_title = 'Gravel', en_title = 'Rubble', ru_title = 'Щебень' },
    [134]   = { group_id = 2, group_title = 'Gravel', en_title = 'Building Site', ru_title = 'Гравий на строительной площадке' },
    [140]   = { group_id = 2, group_title = 'Gravel', en_title = 'Junkyard Piles', ru_title = 'Сваи из гравия в Junkyard' },

    -- Grass
    [9]     = { group_id = 3, group_title = 'Grass', en_title = 'Grass (short lush)', ru_title = 'Трава (короткая пышная)' },
    [10]    = { group_id = 3, group_title = 'Grass', en_title = 'Grass (medium lush)', ru_title = 'Трава (средняя пышная)' },
    [11]    = { group_id = 3, group_title = 'Grass', en_title = 'Grass (long lush)', ru_title = 'Трава (длинная пышная)' },
    [12]    = { group_id = 3, group_title = 'Grass', en_title = 'Grass (short dry)', ru_title = 'Трава (короткая сухая)' },
    [13]    = { group_id = 3, group_title = 'Grass', en_title = 'Grass (medium dry)', ru_title = 'Трава (полусухая)' },
    [14]    = { group_id = 3, group_title = 'Grass', en_title = 'Grass (long dry)', ru_title = 'Трава (длинная сухая)' },
    [15]    = { group_id = 3, group_title = 'Grass', en_title = 'Golf Grass (rough)', ru_title = 'Гольф газон (грубый)' },
    [16]    = { group_id = 3, group_title = 'Grass', en_title = 'Golf Grass (smooth)', ru_title = 'Гольф газон (гладкий)' },
    [17]    = { group_id = 3, group_title = 'Grass', en_title = 'Steep Slidy Grass', ru_title = 'Степная трава' },
    [20]    = { group_id = 3, group_title = 'Grass', en_title = 'Meadow', ru_title = 'Луговая трава' },
    [80]    = { group_id = 3, group_title = 'Grass', en_title = 'Grass (short)', ru_title = 'Трава (короткая)' },
    [81]    = { group_id = 3, group_title = 'Grass', en_title = 'Grass (meadow)', ru_title = 'Трава (луговая)' },
    [82]    = { group_id = 3, group_title = 'Grass', en_title = 'Grass (dry)', ru_title = 'Трава (сухая)' },
    [115]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (wee flowers)', ru_title = 'Трава (крошечные цветы)' },
    [116]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (dry tall)', ru_title = 'Трава (сухая, высокая)' },
    [117]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (lush tall)', ru_title = 'Трава (пышная, высокая)' },
    [118]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (green mix)', ru_title = 'Трава (зеленая, смесь)' },
    [119]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (brown mix)', ru_title = 'Трава (коричневая, смесь)' },
    [120]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (low)', ru_title = 'Трава низкая' },
    [121]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (rocky)', ru_title = 'Трава скалистая' },
    [122]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (small trees)', ru_title = 'Трава (небольшие деревья)' },
    [125]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (weeds)', ru_title = 'Трава (сорняки)' },
    [146]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (light)', ru_title = 'Трава (светлая 1)' },
    [147]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (lighter)', ru_title = 'Трава (светлее 2)' },
    [148]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (lighter 2)', ru_title = 'Трава (светлее 3)' },
    [149]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (mid 1)', ru_title = 'Трава (середняя 1)' },
    [150]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (mid 2)', ru_title = 'Трава (середняя 2)' },
    [151]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (dark)', ru_title = 'Трава (темная 1)' },
    [152]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (dark 2)', ru_title = 'Трава (темнее 2)' },
    [153]   = { group_id = 3, group_title = 'Grass', en_title = 'Grass (dirt mix)', ru_title = 'Трава и смесь грязи' },
    [160]   = { group_id = 3, group_title = 'Grass', en_title = 'Park Grass', ru_title = 'Трава в парке' },

    -- Dirt
    [19]    = { group_id = 4, group_title = 'Dirt', en_title = 'Flower Bed', ru_title = 'Земля цветника' },
    [21]    = { group_id = 4, group_title = 'Dirt', en_title = 'Waste Ground', ru_title = 'Пустырный грунт' },
    [22]    = { group_id = 4, group_title = 'Dirt', en_title = 'Woodland Ground', ru_title = 'Лесной грунт' },
    [24]    = { group_id = 4, group_title = 'Dirt', en_title = 'Mud (wet)', ru_title = 'Земляная грязь (мокрая)' },
    [25]    = { group_id = 4, group_title = 'Dirt', en_title = 'Mud (dry)', ru_title = 'Земляная грязь (сухая)' },
    [26]    = { group_id = 4, group_title = 'Dirt', en_title = 'Dirt', ru_title = 'Грязь' },
    [27]    = { group_id = 4, group_title = 'Dirt', en_title = 'Dirt Track', ru_title = 'Грунтовая дорога' },
    [40]    = { group_id = 4, group_title = 'Dirt', en_title = 'Corn Field', ru_title = 'Кукурузное поле' },
    [83]    = { group_id = 4, group_title = 'Dirt', en_title = 'Woodland', ru_title = 'Земля лесной местности' },
    [84]    = { group_id = 4, group_title = 'Dirt', en_title = 'Wood Dense', ru_title = 'Плотная деревянистая грязь' },
    [87]    = { group_id = 4, group_title = 'Dirt', en_title = 'Flowerbed', ru_title = 'Земля в клумбе' },
    [88]    = { group_id = 4, group_title = 'Dirt', en_title = 'Waste Ground', ru_title = 'Поверхность на пустыре' },
    [100]   = { group_id = 4, group_title = 'Dirt', en_title = 'Riverbed', ru_title = 'Поверхность под водой' },
    [110]   = { group_id = 4, group_title = 'Dirt', en_title = 'Marsh', ru_title = 'Земля в болоте' },
    [123]   = { group_id = 4, group_title = 'Dirt', en_title = 'Dirt (rocky)', ru_title = 'Земля (скалистая)' },
    [124]   = { group_id = 4, group_title = 'Dirt', en_title = 'Dirt (weeds)', ru_title = 'Земля (сорняки)' },
    [126]   = { group_id = 4, group_title = 'Dirt', en_title = 'River Edge', ru_title = 'Обочина у дороги земляная' },
    [128]   = { group_id = 4, group_title = 'Dirt', en_title = 'Forest (stumps)', ru_title = 'Лесная поверхность (пни)' },
    [129]   = { group_id = 4, group_title = 'Dirt', en_title = 'Forest (sticks)', ru_title = 'Лесная поверхность (веточки)' },
    [130]   = { group_id = 4, group_title = 'Dirt', en_title = 'Forest (leaves)', ru_title = 'Лесная поверхность (листья)' },
    [132]   = { group_id = 4, group_title = 'Dirt', en_title = 'Forest (dry)', ru_title = 'Лесная поверхность (высушенная)' },
    [133]   = { group_id = 4, group_title = 'Dirt', en_title = 'Sparse Flowers', ru_title = 'Поверхность с редкими цветами' },
    [141]   = { group_id = 4, group_title = 'Dirt', en_title = 'Junkyard Ground', ru_title = 'Земля в Junkyard' },
    [142]   = { group_id = 4, group_title = 'Dirt', en_title = 'Dump', ru_title = 'Поверхность мусорной кучи' },
    [145]   = { group_id = 4, group_title = 'Dirt', en_title = 'Cornfield', ru_title = 'Поверхность поля (сено,солома)' },
    [155]   = { group_id = 4, group_title = 'Dirt', en_title = 'Riverbed (shallow)', ru_title = 'Поверхность русла реки (мелкое)' },
    [156]   = { group_id = 4, group_title = 'Dirt', en_title = 'Riverbed (weeds)', ru_title = 'Под водой сорняки' },

    -- Sand
    [28]    = { group_id = 5, group_title = 'Sand', en_title = 'Sand (deep)', ru_title = 'Песок (глубокий)' },
    [29]    = { group_id = 5, group_title = 'Sand', en_title = 'Sand (medium)', ru_title = 'Песок (средний)' },
    [30]    = { group_id = 5, group_title = 'Sand', en_title = 'Sand (compact)', ru_title = 'Песок (компактный)' },
    [31]    = { group_id = 5, group_title = 'Sand', en_title = 'Sand (arid)', ru_title = 'Песок (засушливый)' },
    [32]    = { group_id = 5, group_title = 'Sand', en_title = 'Sand (more)', ru_title = 'Песок (подробный)' },
    [33]    = { group_id = 5, group_title = 'Sand', en_title = 'Sand (beach)', ru_title = 'Песок (пляжный)' },
    [74]    = { group_id = 5, group_title = 'Sand', en_title = 'Sand', ru_title = 'Песок' },
    [75]    = { group_id = 5, group_title = 'Sand', en_title = 'Sand (dense)', ru_title = 'Песок(плотный)' },
    [76]    = { group_id = 5, group_title = 'Sand', en_title = 'Sand (arid)', ru_title = 'Песок(засушливый)' },
    [77]    = { group_id = 5, group_title = 'Sand', en_title = 'Sand (compact)', ru_title = 'Песок(компактный)' },
    [78]    = { group_id = 5, group_title = 'Sand', en_title = 'Sand (rocky)', ru_title = 'Песок(скалистый)' },
    [79]    = { group_id = 5, group_title = 'Sand', en_title = 'Sand (beach)', ru_title = 'Песок(пляжный)' },
    [86]    = { group_id = 5, group_title = 'Sand', en_title = 'Roadside Des', ru_title = 'Песчаная обочина дороги' },
    [96]    = { group_id = 5, group_title = 'Sand', en_title = 'Underwater (lush)', ru_title = 'Подводный мир (пышные)' },
    [97]    = { group_id = 5, group_title = 'Sand', en_title = 'Underwater (barren)', ru_title = 'Подводный мир (бесплодный)' },
    [98]    = { group_id = 5, group_title = 'Sand', en_title = 'Underwater (coral)', ru_title = 'Подводный мир (коралл)' },
    [99]    = { group_id = 5, group_title = 'Sand', en_title = 'Underwater (deep)', ru_title = 'Подводный мир (глубокий)' },
    [131]   = { group_id = 5, group_title = 'Sand', en_title = 'Desert Rocks', ru_title = 'Скалы в пустыне' },
    [143]   = { group_id = 5, group_title = 'Sand', en_title = 'Cactus Dense', ru_title = 'Кактусы густые' },
    [157]   = { group_id = 5, group_title = 'Sand', en_title = 'Seaweed', ru_title = 'Водоросли под водой' },

    -- Glass
    [45]    = { group_id = 6, group_title = 'Glass', en_title = 'Glass', ru_title = 'Стекло' },
    [46]    = { group_id = 6, group_title = 'Glass', en_title = 'Glass Windows (large)', ru_title = 'Большое стеклянное окно' },
    [47]    = { group_id = 6, group_title = 'Glass', en_title = 'Glass Windows (small)', ru_title = 'Маленькое стеклянное окно' },
    [175]   = { group_id = 6, group_title = 'Glass', en_title = 'Unbreakable Glass', ru_title = 'Небьющееся стекло' },

    -- Wood
    [42]    = { group_id = 7, group_title = 'Wood', en_title = 'Wood (crates)', ru_title = 'Деревянный ящик' },
    [43]    = { group_id = 7, group_title = 'Wood', en_title = 'Wood (solid)', ru_title = 'Твердая деревянная поверхность' },
    [44]    = { group_id = 7, group_title = 'Wood', en_title = 'Wood (thin)', ru_title = 'Тонкая деревянная поверхность' },
    [70]    = { group_id = 7, group_title = 'Wood', en_title = 'Wood (bench)', ru_title = 'Деревянная скамейка' },
    [72]    = { group_id = 7, group_title = 'Wood', en_title = 'Floorboard', ru_title = 'Паркетная доска' },
    [73]    = { group_id = 7, group_title = 'Wood', en_title = 'Stairs (wood)', ru_title = 'Деревянные ступеньки/лестница' },
    [172]   = { group_id = 7, group_title = 'Wood', en_title = 'Wood Picket Fence', ru_title = 'Деревянный кол для забора' },
    [173]   = { group_id = 7, group_title = 'Wood', en_title = 'Wood Slatted Fence', ru_title = 'Деревянные решетки для забора' },
    [174]   = { group_id = 7, group_title = 'Wood', en_title = 'Wood Ranch Fence', ru_title = 'Деревянный забор на ранчо' },

    -- Metal
    [50]    = { group_id = 8, group_title = 'Metal', en_title = 'Garage Door', ru_title = 'Гаражные ворота' },
    [51]    = { group_id = 8, group_title = 'Metal', en_title = 'Thick Metal Plate', ru_title = 'Толстый лист металла' },
    [52]    = { group_id = 8, group_title = 'Metal', en_title = 'Scaffold Pole', ru_title = 'Строительные леса' },
    [53]    = { group_id = 8, group_title = 'Metal', en_title = 'Lamp Post', ru_title = 'Фонарный столб' },
    [54]    = { group_id = 8, group_title = 'Metal', en_title = 'Metal Gate', ru_title = 'Металлические ворота' },
    [55]    = { group_id = 8, group_title = 'Metal', en_title = 'Metal Chain fence', ru_title = 'Металлические цепи/заборы' },
    [56]    = { group_id = 8, group_title = 'Metal', en_title = 'Girder', ru_title = 'Металлическая балка' },
    [57]    = { group_id = 8, group_title = 'Metal', en_title = 'Fire Hydrant', ru_title = 'Пожарный гидрант' },
    [58]    = { group_id = 8, group_title = 'Metal', en_title = 'Container', ru_title = 'Контейнер металлический' },
    [59]    = { group_id = 8, group_title = 'Metal', en_title = 'News Vendor', ru_title = 'Новостной столб' },
    [63]    = { group_id = 8, group_title = 'Metal', en_title = 'Car', ru_title = 'Автомобиль' },
    [64]    = { group_id = 8, group_title = 'Metal', en_title = 'Car (panel)', ru_title = 'Автомобильная панель' },
    [65]    = { group_id = 8, group_title = 'Metal', en_title = 'Car (moving component)', ru_title = 'Автомобиль (движущиеся компоненты)' },
    [162]   = { group_id = 8, group_title = 'Metal', en_title = 'Stairs (metal)', ru_title = 'Лестница (металлическая)' },
    [164]   = { group_id = 8, group_title = 'Metal', en_title = 'Floor (metal)', ru_title = 'Балкон (металлический)' },
    [167]   = { group_id = 8, group_title = 'Metal', en_title = 'Thin Metal Sheet', ru_title = 'Тонкий лист металла' },
    [168]   = { group_id = 8, group_title = 'Metal', en_title = 'Metal Barrel', ru_title = 'Металлическая бочка' },
    [171]   = { group_id = 8, group_title = 'Metal', en_title = 'Metal Dumpster', ru_title = 'Металлическая корзина' },

    -- Stone
    [18]    = { group_id = 9, group_title = 'Stone', en_title = 'Steep Cliff', ru_title = 'Крутые скалы/утесы' },
    [35]    = { group_id = 9, group_title = 'Stone', en_title = 'Rock (dry)', ru_title = 'Гора (сухая)' },
    [36]    = { group_id = 9, group_title = 'Stone', en_title = 'Rock (wet)', ru_title = 'Гора (мокрая)' },
    [37]    = { group_id = 9, group_title = 'Stone', en_title = 'Rock (cliff)', ru_title = 'Гора (Скала)' },
    [69]    = { group_id = 9, group_title = 'Stone', en_title = 'Transparent Stone', ru_title = 'Прозрачный камень' },
    [109]   = { group_id = 9, group_title = 'Stone', en_title = 'Mountain', ru_title = 'Горная поверхность' },
    [154]   = { group_id = 9, group_title = 'Stone', en_title = 'Riverbed (stone)', ru_title = 'Поверхность под водой (камень)' },
    [161]   = { group_id = 9, group_title = 'Stone', en_title = 'Stairs (stone)', ru_title = 'Лестница (камень)' },

    -- Vegetation
    [23]    = { group_id = 10, group_title = 'Vegetation', en_title = 'Vegetation', ru_title = 'Растительность' },
    [41]    = { group_id = 10, group_title = 'Vegetation', en_title = 'Hedge', ru_title = 'Хедж' },
    [111]   = { group_id = 10, group_title = 'Vegetation', en_title = 'Bushy', ru_title = 'Буши' },
    [112]   = { group_id = 10, group_title = 'Vegetation', en_title = 'Bushy (mix)', ru_title = 'Буши (микс)' },
    [113]   = { group_id = 10, group_title = 'Vegetation', en_title = 'Bushy (dry)', ru_title = 'Буши (сухая)' },
    [114]   = { group_id = 10, group_title = 'Vegetation', en_title = 'Bushy (mid)', ru_title = 'Буши (средняя)' },

    -- Water 
    [38]    = { group_id = 11, group_title = 'Water', en_title = 'Water (riverbed)', ru_title = 'Вода (русло)' },
    [39]    = { group_id = 11, group_title = 'Water', en_title = 'Water (shallow)', ru_title = 'Вода (мелкая)' },

    -- Misc
    [48]    = { group_id = 12, group_title = 'Misc', en_title = 'Empty1', ru_title = 'Неизвестно1' },
    [49]    = { group_id = 12, group_title = 'Misc', en_title = 'Empty2', ru_title = 'Неизвестно2' },
    [60]    = { group_id = 12, group_title = 'Misc', en_title = 'Wheelbase', ru_title = 'Колесная база' },
    [61]    = { group_id = 12, group_title = 'Misc', en_title = 'Cardboard Box', ru_title = 'Картонная коробка' },
    [62]    = { group_id = 12, group_title = 'Misc', en_title = 'Ped', ru_title = 'Пед' },
    [66]    = { group_id = 12, group_title = 'Misc', en_title = 'Transparent Cloth', ru_title = 'Прозрачная ткань (шторы, скатерть)' },
    [67]    = { group_id = 12, group_title = 'Misc', en_title = 'Rubber', ru_title = 'Резина' },
    [68]    = { group_id = 12, group_title = 'Misc', en_title = 'Plastic', ru_title = 'Пластик' },
    [71]    = { group_id = 12, group_title = 'Misc', en_title = 'Carpet', ru_title = 'Ковролин' },
    [90]    = { group_id = 12, group_title = 'Misc', en_title = 'Office Desk', ru_title = 'Рабочий стол' },
    [91]    = { group_id = 12, group_title = 'Misc', en_title = '711 Shelf 1', ru_title = 'Полка в 711-1' },
    [92]    = { group_id = 12, group_title = 'Misc', en_title = '711 Shelf 2', ru_title = 'Полка в 711-2' },
    [93]    = { group_id = 12, group_title = 'Misc', en_title = '711 Shelf 3', ru_title = 'Полка в 711-3' },
    [94]    = { group_id = 12, group_title = 'Misc', en_title = 'Restuarant Table', ru_title = 'Стол для ресторана' },
    [95]    = { group_id = 12, group_title = 'Misc', en_title = 'Bar Table', ru_title = 'Стол для бара/кафе' },
    [102]   = { group_id = 12, group_title = 'Misc', en_title = 'Bedroom Floor', ru_title = 'Спальня на первом этаже' },
    [103]   = { group_id = 12, group_title = 'Misc', en_title = 'Kitchen Floor', ru_title = 'Полы на кухне' },
    [104]   = { group_id = 12, group_title = 'Misc', en_title = 'Livingroom Floor', ru_title = 'Полы в гостиной' },
    [105]   = { group_id = 12, group_title = 'Misc', en_title = 'Corridor Floor', ru_title = 'Полы в коридоре' },
    [106]   = { group_id = 12, group_title = 'Misc', en_title = '711 Floor', ru_title = 'Полы в 711' },
    [107]   = { group_id = 12, group_title = 'Misc', en_title = 'Fast Food Floor', ru_title = 'Полы в Fast Food' },
    [108]   = { group_id = 12, group_title = 'Misc', en_title = 'Skanky Floor', ru_title = 'Полы в Skanky' },
    [158]   = { group_id = 12, group_title = 'Misc', en_title = 'Door', ru_title = 'Дверь' },
    [159]   = { group_id = 12, group_title = 'Misc', en_title = 'Plastic Barrier', ru_title = 'Пластиковый барьер' },
    [163]   = { group_id = 12, group_title = 'Misc', en_title = 'Stairs (carpet)', ru_title = 'Лестница (ковер на лестнице)' },
    [166]   = { group_id = 12, group_title = 'Misc', en_title = 'Bin Bag', ru_title = 'Мешок для мусора' },
    [169]   = { group_id = 12, group_title = 'Misc', en_title = 'Plastic Cone', ru_title = 'Пластиковый конус' },
    [170]   = { group_id = 12, group_title = 'Misc', en_title = 'Plastic Dumpster', ru_title = 'Пластиковая корзина' },
    [176]   = { group_id = 12, group_title = 'Misc', en_title = 'Hay Bale', ru_title = 'Тюк сена/соломы' },
    [177]   = { group_id = 12, group_title = 'Misc', en_title = 'Gore', ru_title = 'Гора' },
    [178]   = { group_id = 12, group_title = 'Misc', en_title = 'Rail Track', ru_title = 'Железнодорожный путь' },

}

